import React, { useState } from 'react'
import { FileText, Layout, Swords, Presentation, Clock, ChevronDown, ChevronRight, CheckCircle2, AlertTriangle, Lightbulb, MessageSquare, RotateCcw } from 'lucide-react'

const TABS = [
  { id: 'demo', label: 'Demo script', icon: Layout },
  { id: 'compete', label: 'Battle card', icon: Swords },
  { id: 'content', label: 'Deliverables', icon: Presentation },
  { id: 'research', label: 'Research', icon: FileText },
  { id: 'trace', label: 'Agent trace', icon: Clock },
]

export default function OutputDisplay({ result, dealData, onReset }) {
  const [activeTab, setActiveTab] = useState('demo')

  const availableTabs = TABS.filter(tab => {
    if (tab.id === 'demo') return result.demo_script
    if (tab.id === 'compete') return result.competitive_intel
    if (tab.id === 'content') return result.content_output
    if (tab.id === 'research') return result.research_brief
    if (tab.id === 'trace') return result.agent_trace
    return false
  })

  return (
    <div>
      {/* Success Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold text-white" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
            {dealData.company_name} — Demo prep ready
          </h2>
          <p className="text-sm text-white/30 mt-1">
            {availableTabs.length} outputs generated by {result.agent_trace?.length || 0} AI agents
          </p>
        </div>
        <button
          onClick={onReset}
          className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-white/[0.04] border border-white/[0.06] text-xs text-white/40 hover:text-white/70 transition-all"
        >
          <RotateCcw size={12} />
          New deal
        </button>
      </div>

      {/* Tab Navigation */}
      <div className="flex gap-1 mb-6 p-1 bg-white/[0.02] rounded-xl border border-white/[0.04]">
        {availableTabs.map(tab => {
          const Icon = tab.icon
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-medium transition-all flex-1 justify-center ${
                activeTab === tab.id
                  ? 'bg-blue-500/15 text-blue-400 border border-blue-500/25'
                  : 'text-white/30 hover:text-white/50 border border-transparent'
              }`}
            >
              <Icon size={13} />
              {tab.label}
            </button>
          )
        })}
      </div>

      {/* Tab Content */}
      <div className="min-h-[400px]">
        {activeTab === 'demo' && result.demo_script && (
          <DemoScriptView data={result.demo_script} />
        )}
        {activeTab === 'compete' && result.competitive_intel && (
          <CompeteView data={result.competitive_intel} />
        )}
        {activeTab === 'content' && result.content_output && (
          <ContentView data={result.content_output} />
        )}
        {activeTab === 'research' && result.research_brief && (
          <ResearchView data={result.research_brief} />
        )}
        {activeTab === 'trace' && (
          <TraceView trace={result.agent_trace} />
        )}
      </div>
    </div>
  )
}

// ---- Demo Script View ----
function DemoScriptView({ data }) {
  if (data.raw_response) return <RawView text={data.raw_response} />
  if (data.error) return <ErrorView message={data.error} />

  // Handle discovery framework output
  if (data.discovery_framework) {
    return <DiscoveryView data={data} />
  }

  return (
    <div className="space-y-4">
      {/* Demo Header */}
      {data.demo_title && (
        <Card>
          <div className="flex items-start justify-between">
            <div>
              <h3 className="text-lg font-semibold text-white">{data.demo_title}</h3>
              <p className="text-sm text-white/30 mt-1">
                {data.duration_minutes} min • {data.audience_level} audience
              </p>
            </div>
            <span className="px-2.5 py-1 rounded-md bg-blue-500/10 text-[11px] text-blue-400 border border-blue-500/20">
              {data.demo_modules?.length || 0} modules
            </span>
          </div>
        </Card>
      )}

      {/* Opening */}
      {data.opening && (
        <Card title="Opening" badge={`${data.opening.duration_minutes || 5} min`}>
          {data.opening.hook && (
            <div className="mb-3">
              <Label>Hook</Label>
              <p className="text-sm text-white/70">{data.opening.hook}</p>
            </div>
          )}
          {data.opening.agenda_framing && (
            <div>
              <Label>Agenda framing</Label>
              <p className="text-sm text-white/70">{data.opening.agenda_framing}</p>
            </div>
          )}
        </Card>
      )}

      {/* Demo Modules */}
      {data.demo_modules?.map((mod, idx) => (
        <ModuleCard key={idx} module={mod} index={idx} />
      ))}

      {/* Closing */}
      {data.closing && (
        <Card title="Closing">
          {data.closing.value_summary && (
            <div className="mb-3">
              <Label>Value summary</Label>
              <p className="text-sm text-white/70">{data.closing.value_summary}</p>
            </div>
          )}
          {data.closing.call_to_action && (
            <div className="mb-3">
              <Label>Call to action</Label>
              <p className="text-sm text-emerald-300/70">{data.closing.call_to_action}</p>
            </div>
          )}
          {data.closing.objection_preemption && (
            <div>
              <Label>Objection preemption</Label>
              <p className="text-sm text-amber-300/70">{data.closing.objection_preemption}</p>
            </div>
          )}
        </Card>
      )}

      {/* Backup Modules */}
      {data.backup_modules?.length > 0 && (
        <Card title="Backup modules (if asked)">
          {data.backup_modules.map((mod, idx) => (
            <div key={idx} className={`${idx > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
              <p className="text-sm text-white/70 font-medium">{mod.module_name}</p>
              <p className="text-xs text-white/30 mt-0.5">{mod.trigger}</p>
            </div>
          ))}
        </Card>
      )}
    </div>
  )
}

function ModuleCard({ module, index }) {
  const [expanded, setExpanded] = useState(index === 0)

  return (
    <div className="rounded-xl bg-white/[0.02] border border-white/[0.05] overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full p-4 flex items-center gap-3 hover:bg-white/[0.01] transition-all text-left"
      >
        <span className="w-7 h-7 rounded-lg bg-blue-500/10 flex items-center justify-center text-[11px] text-blue-400 font-bold flex-shrink-0">
          {module.sequence_number || index + 1}
        </span>
        <div className="flex-1 min-w-0">
          <h4 className="text-sm font-medium text-white">{module.module_name}</h4>
          <p className="text-[11px] text-white/30 truncate">{module.why_show_this}</p>
        </div>
        <span className="text-[10px] text-white/20 flex-shrink-0">{module.duration_minutes} min</span>
        {expanded ? <ChevronDown size={14} className="text-white/20" /> : <ChevronRight size={14} className="text-white/20" />}
      </button>

      {expanded && (
        <div className="px-4 pb-4 space-y-3 border-t border-white/[0.04] pt-3">
          {module.talk_track && (
            <div>
              <Label icon={<MessageSquare size={10} />}>Talk track</Label>
              <p className="text-sm text-white/60 leading-relaxed bg-white/[0.02] rounded-lg p-3 border-l-2 border-blue-500/30">
                {module.talk_track}
              </p>
            </div>
          )}
          {module.key_features_to_highlight?.length > 0 && (
            <div>
              <Label icon={<CheckCircle2 size={10} />}>Key features to highlight</Label>
              <div className="flex flex-wrap gap-1.5">
                {module.key_features_to_highlight.map((f, i) => (
                  <span key={i} className="px-2 py-1 rounded-md bg-white/[0.04] text-[11px] text-white/50">{f}</span>
                ))}
              </div>
            </div>
          )}
          {module.competitive_trap && (
            <div>
              <Label icon={<AlertTriangle size={10} />}>Competitive trap</Label>
              <p className="text-sm text-amber-300/60">{module.competitive_trap}</p>
            </div>
          )}
          {module.customer_story && (
            <div>
              <Label icon={<Lightbulb size={10} />}>Customer story</Label>
              <p className="text-sm text-teal-300/60">{module.customer_story}</p>
            </div>
          )}
          {module.transition_to_next && (
            <div>
              <Label>Transition</Label>
              <p className="text-sm text-white/40 italic">{module.transition_to_next}</p>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ---- Discovery View ----
function DiscoveryView({ data }) {
  const framework = data.discovery_framework || {}
  const meddpicc = data.meddpicc_mapping || {}

  return (
    <div className="space-y-4">
      {Object.entries(framework).map(([category, questions]) => (
        <Card key={category} title={category.replace(/_/g, ' ')}>
          {Array.isArray(questions) && questions.map((q, i) => (
            <p key={i} className={`text-sm text-white/60 ${i > 0 ? 'mt-2' : ''}`}>
              <span className="text-white/25 mr-2">{i + 1}.</span>{q}
            </p>
          ))}
        </Card>
      ))}

      {Object.keys(meddpicc).length > 0 && (
        <Card title="MEDDPICC mapping">
          {Object.entries(meddpicc).map(([key, value]) => (
            <div key={key} className="mb-2 last:mb-0">
              <span className="text-[11px] text-blue-400/60 uppercase tracking-wider">{key.replace(/_/g, ' ')}</span>
              <p className="text-sm text-white/60">{value}</p>
            </div>
          ))}
        </Card>
      )}
    </div>
  )
}

// ---- Competitive Intel View ----
function CompeteView({ data }) {
  if (data.raw_response) return <RawView text={data.raw_response} />
  if (data.error) return <ErrorView message={data.error} />

  return (
    <div className="space-y-4">
      {data.primary_competitor && (
        <Card>
          <h3 className="text-lg font-semibold text-white mb-1">vs {data.primary_competitor}</h3>
          <p className="text-sm text-white/40">{data.competitor_summary}</p>
        </Card>
      )}

      {data.harness_advantages?.length > 0 && (
        <Card title="Harness advantages">
          {data.harness_advantages.map((adv, i) => (
            <div key={i} className={`${i > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
              <p className="text-sm text-emerald-300/70 font-medium">{adv.advantage}</p>
              <p className="text-xs text-white/30 mt-0.5">{adv.proof_point}</p>
            </div>
          ))}
        </Card>
      )}

      {data.evaluation_criteria_to_set?.length > 0 && (
        <Card title="Evaluation criteria to set">
          {data.evaluation_criteria_to_set.map((c, i) => (
            <div key={i} className={`${i > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
              <p className="text-sm text-white/70 font-medium">{c.criterion}</p>
              <p className="text-xs text-blue-300/50 mt-0.5">{c.why_harness_wins}</p>
            </div>
          ))}
        </Card>
      )}

      {data.objection_handling?.length > 0 && (
        <Card title="Objection handling">
          {data.objection_handling.map((obj, i) => (
            <div key={i} className={`${i > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
              <p className="text-sm text-amber-300/60">
                <span className="text-[10px] text-amber-400/40 uppercase tracking-wider mr-1">Objection:</span>
                {obj.objection}
              </p>
              <p className="text-sm text-white/60 mt-1">
                <span className="text-[10px] text-emerald-400/40 uppercase tracking-wider mr-1">Response:</span>
                {obj.response}
              </p>
            </div>
          ))}
        </Card>
      )}

      {data.landmines_to_set?.length > 0 && (
        <Card title="Landmines — questions for customer to ask competitor">
          {data.landmines_to_set.map((lm, i) => (
            <div key={i} className={`${i > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
              <p className="text-sm text-white/60">{lm.question_for_customer_to_ask_competitor}</p>
              <p className="text-xs text-red-300/40 mt-0.5">Expected gap: {lm.expected_gap}</p>
            </div>
          ))}
        </Card>
      )}
    </div>
  )
}

// ---- Content View ----
function ContentView({ data }) {
  if (data.raw_response) return <RawView text={data.raw_response} />
  if (data.error) return <ErrorView message={data.error} />

  return (
    <div className="space-y-4">
      {/* Slide Deck */}
      {data.slide_deck && (
        <div>
          <h3 className="text-sm font-medium text-white/40 uppercase tracking-wider mb-3">Slide deck</h3>
          {data.slide_deck.title_slide && (
            <Card>
              <p className="text-lg font-semibold text-white">{data.slide_deck.title_slide.title}</p>
              <p className="text-sm text-white/40">{data.slide_deck.title_slide.subtitle}</p>
            </Card>
          )}
          {data.slide_deck.slides?.map((slide, i) => (
            <div key={i} className="mt-3">
              <Card title={`Slide ${slide.slide_number || i + 1}: ${slide.title}`} badge={slide.content_type}>
                <div className="mb-2">
                  <p className="text-sm text-white/60 whitespace-pre-wrap">{slide.content}</p>
                </div>
                {slide.speaker_notes && (
                  <div className="mt-3 pt-3 border-t border-white/[0.04]">
                    <Label>Speaker notes</Label>
                    <p className="text-xs text-white/30 italic">{slide.speaker_notes}</p>
                  </div>
                )}
              </Card>
            </div>
          ))}
        </div>
      )}

      {/* Leave Behind */}
      {data.leave_behind_document && (
        <div className="mt-6">
          <h3 className="text-sm font-medium text-white/40 uppercase tracking-wider mb-3">Leave-behind document</h3>
          <Card title={data.leave_behind_document.title}>
            {data.leave_behind_document.executive_summary && (
              <div className="mb-3 p-3 rounded-lg bg-blue-500/5 border border-blue-500/10">
                <Label>Executive summary</Label>
                <p className="text-sm text-white/60">{data.leave_behind_document.executive_summary}</p>
              </div>
            )}
            {data.leave_behind_document.sections?.map((sec, i) => (
              <div key={i} className={`${i > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
                <p className="text-sm font-medium text-white/70">{sec.heading}</p>
                <p className="text-sm text-white/40 mt-1">{sec.content}</p>
              </div>
            ))}
          </Card>
        </div>
      )}

      {/* Follow-up Email */}
      {data.follow_up_email && (
        <div className="mt-6">
          <h3 className="text-sm font-medium text-white/40 uppercase tracking-wider mb-3">Follow-up email</h3>
          <Card>
            <p className="text-sm text-white/50 mb-2">
              <span className="text-white/25">Subject:</span> {data.follow_up_email.subject}
            </p>
            <div className="p-3 rounded-lg bg-white/[0.02] border border-white/[0.04]">
              <p className="text-sm text-white/50 whitespace-pre-wrap leading-relaxed">{data.follow_up_email.body}</p>
            </div>
          </Card>
        </div>
      )}
    </div>
  )
}

// ---- Research View ----
function ResearchView({ data }) {
  if (data.raw_response) return <RawView text={data.raw_response} />
  if (data.error) return <ErrorView message={data.error} />

  return (
    <div className="space-y-4">
      {data.company_summary && (
        <Card title="Company context">
          <p className="text-sm text-white/60">{data.company_summary}</p>
        </Card>
      )}

      {data.industry_devops_maturity && (
        <Card title="Industry DevOps maturity">
          <p className="text-sm text-white/60">{data.industry_devops_maturity}</p>
        </Card>
      )}

      {data.likely_pain_points?.length > 0 && (
        <Card title="Likely pain points">
          {data.likely_pain_points.map((p, i) => (
            <p key={i} className="text-sm text-white/60 mb-1.5 last:mb-0">
              <span className="text-amber-400/50 mr-1.5">•</span>{p}
            </p>
          ))}
        </Card>
      )}

      {data.recommended_harness_modules?.length > 0 && (
        <Card title="Recommended Harness modules">
          {data.recommended_harness_modules.map((mod, i) => (
            <div key={i} className={`flex items-start gap-3 ${i > 0 ? 'mt-3 pt-3 border-t border-white/[0.04]' : ''}`}>
              <span className={`mt-0.5 px-1.5 py-0.5 rounded text-[9px] font-bold uppercase tracking-wider ${
                mod.priority === 'high' ? 'bg-emerald-500/15 text-emerald-400' :
                mod.priority === 'medium' ? 'bg-blue-500/15 text-blue-400' :
                'bg-white/[0.05] text-white/30'
              }`}>{mod.priority}</span>
              <div>
                <p className="text-sm text-white/70 font-medium">{mod.module}</p>
                <p className="text-xs text-white/30">{mod.relevance}</p>
              </div>
            </div>
          ))}
        </Card>
      )}

      {data.relevant_customer_stories?.length > 0 && (
        <Card title="Relevant customer stories">
          {data.relevant_customer_stories.map((story, i) => (
            <div key={i} className={`${i > 0 ? 'mt-2 pt-2 border-t border-white/[0.04]' : ''}`}>
              <p className="text-sm text-white/60">
                <span className="text-teal-300/60 font-medium">{story.customer}</span>
                <span className="text-white/20 mx-1.5">•</span>
                <span className="text-white/30">{story.industry}</span>
              </p>
              <p className="text-xs text-white/40 mt-0.5">{story.result}</p>
            </div>
          ))}
        </Card>
      )}
    </div>
  )
}

// ---- Agent Trace View ----
function TraceView({ trace }) {
  if (!trace?.length) return <p className="text-sm text-white/30">No trace data available.</p>

  return (
    <div className="space-y-2">
      <Card title="Agent execution trace">
        {trace.map((t, i) => (
          <div key={i} className={`flex items-center justify-between ${i > 0 ? 'mt-2 pt-2 border-t border-white/[0.04]' : ''}`}>
            <div className="flex items-center gap-2">
              {t.status === 'success' ? (
                <CheckCircle2 size={14} className="text-emerald-400" />
              ) : (
                <AlertTriangle size={14} className="text-red-400" />
              )}
              <span className="text-sm text-white/60 capitalize">{t.agent}</span>
            </div>
            <span className="text-xs text-white/25">{t.duration_seconds}s</span>
          </div>
        ))}
      </Card>
    </div>
  )
}

// ---- Shared Components ----
function Card({ title, badge, children }) {
  return (
    <div className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.05]">
      {(title || badge) && (
        <div className="flex items-center justify-between mb-3">
          {title && <h4 className="text-xs font-medium text-white/30 uppercase tracking-wider">{title}</h4>}
          {badge && <span className="px-2 py-0.5 rounded text-[10px] text-white/25 bg-white/[0.03]">{badge}</span>}
        </div>
      )}
      {children}
    </div>
  )
}

function Label({ children, icon }) {
  return (
    <div className="flex items-center gap-1 mb-1.5">
      {icon && <span className="text-white/20">{icon}</span>}
      <span className="text-[10px] text-white/25 uppercase tracking-wider font-medium">{children}</span>
    </div>
  )
}

function RawView({ text }) {
  return (
    <Card title="Raw response">
      <pre className="text-sm text-white/50 whitespace-pre-wrap font-mono leading-relaxed overflow-auto max-h-[600px]">
        {text}
      </pre>
    </Card>
  )
}

function ErrorView({ message }) {
  return (
    <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/15">
      <p className="text-sm text-red-400/70">{message}</p>
    </div>
  )
}
